### ISSUE TITLE
Information on Java 15

### ISSUE THREAD

**Issue by jbduncan** [binkley/modern-java-practices#1]
Hi @binkley, just came across this repository, looks great!

Having read the README, I'm finding myself querying a bullet point that says, "Java 15 is the current LTS ("long-term support") version". I was under the impression that Java 11 was the latest LTS version, and that the next one will be Java 17. Have I misunderstood something here?

**Comment by jbduncan** [comment]
The following StackOverflow comment by Brian Goetz himself seems to confirm my understanding: https://stackoverflow.com/questions/61267662/why-is-java-14-not-lts#comment108395893_61267662.

**Comment by binkley** [comment]
@jbduncan Oh, ho!  You are so right.  :)

I misread https://www.oracle.com/java/technologies/java-se-support-roadmap.html :(

Thank you for spotting this!  I'll fix forthwith.

**Comment by jbduncan** [comment]
You're very welcome! Thank you for the quick response.
