### ISSUE TITLE
Information on Java 8

### ISSUE THREAD

**Issue by jbduncan** [binkley/modern-java-practices#2]
Following on from my last issue #1, I was also under the impression that AdoptOpenJDK 8 was still being supported, which the following link on the website seems to confirm: https://adoptopenjdk.net/support.html. However I'm not sure if this applies to all distributions of OpenJDK 8. Any thoughts on whether this info should be included on the README or not?

**Comment by binkley** [comment]
@jbduncan Good call out, and I'll update the language to be more clear.

For me I was considering "supported" to mean "supported by Oracle".  I'm a consultant, and I recommend to clients to move off of Java 8.  You're right that there is a broader mindset than this!

**Comment by binkley** [comment]
@jbduncan Do you have suggested language here?

**Comment by jbduncan** [comment]
@binkley Hmm... How about changing this bullet point...

> - Update from Java 8 and older: These are no longer supported unless one buys paid support contracts from Oracle

to the following? (I'm using Markdown to emphasise how I think the changes should be done.)

> `- Update from Java 8 or older: These are no longer supported unless one buys paid support contracts from [Oracle](https://www.oracle.com/java/technologies/java-se-support-roadmap.htm). AdoptOpenJDK still provides a distribution of OpenJDK 8, but only until [at least May 2026](https://adoptopenjdk.net/support.html?variant=openjdk8&jvmVariant=hotspot)`

**Comment by binkley** [comment]
Done with some wordsmithing.  Thank you!

**Comment by jbduncan** [comment]
You're very welcome!

Just a couple of minor nitpicks from me:

- On the bullet point "For Java 8 or older", there's a stray space after the [Oracle](https://www.oracle.com/java/technologies/java-se-support-roadmap.htm) link.
- On the same bullet point, either the word "contracts" should be renamed to "contract" (no 's') or the "a" should be removed.

But other than that, it looks better than what I suggested, so well done! :+1:

**Comment by jbduncan** [comment]
To add to my last comment, this might be me being British and not understanding American English very well, but where it says, "which is through at least May 2026", it doesn't sound quite right to me. In my mind, the following reads better:

> which is supported through at least May 2026

or even better:

> which is supported until at least May 2026

What do you think?

**Comment by binkley** [comment]
@jbduncan Done!

**Comment by jbduncan** [comment]
@binkley Thanks! But I'm sorry to say that my earlier comment https://github.com/binkley/modern-java-practices/issues/2#issuecomment-707299697 still stands...

**Comment by binkley** [comment]
I appreciate this level of keen detail.  :)

I failed to follow Treebeard's advice: _Don't be hasty_

I'm not sure about the space after "Oracle".  I'm using IntelliJ to edit Markdown, and it is _insisting_ on breaking the period at the end of the sentence to the next line.  :(  Of course, I can fix this in `vi`; however, the next time I edit in IntelliJ, that IDE will undo my fix.

*Unrelated*: I wanted to use Spotless, but am using SUN formatting conventions (I feel they are more common for most readers).  Is there a way to have Spotless use SUN rather than Google conventions?  I miss Kotlin, where there is "one right way" to format, and tooling to support that.

**Comment by binkley** [comment]
@jbduncan I filed an issue with JB about the period ("full stop") being forcibly wrapped to a new line: https://youtrack.jetbrains.com/issue/IDEA-252889

**Comment by jbduncan** [comment]
Good question regarding Spotless! As far as I'm aware there isn't a built-in way of making Spotless format with SUN conventions. May I suggest raising an issue on https://github.com/diffplug/spotless about this? I'd be more than happy to talk about it over there. (Alternatively we have a [Gitter channel](https://gitter.im/diffplug/spotless).)

**Comment by binkley** [comment]
@jbduncan Thanks! -- https://github.com/diffplug/spotless/issues/718

**Comment by binkley** [comment]
@jbduncan Unfortunately, the issue with breaking the line before a period ("full stop") in JB's IDEs editor for markdown still remains, even in the latest release.  :(

https://github.com/binkley/modern-java-practices/issues/2#issuecomment-708391074

**Comment by binkley** [comment]
I'd like to close this issue if you're happy with the present wording around Java 8.  @jbduncan

**Comment by jbduncan** [comment]
@binkley Yep, I'm happy with the current wording, so I'll close the issue for you.

Many thanks for taking my feedback so constructively!
