### ISSUE TITLE
Dependabot does not create Gradle PRs

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#217]
Dependabot offers PRs for Maven, but not for Gradle.  Find out why this is, and address.

**Comment by lianup** [comment]
Hi binkley,dependabot only supports scanning the version number of `build.gradle` and `settings.gradle` files. Is there any other solution besides manually updating the version number?
Or, in this case, putting the version number in `gradle.properties` is not a good choice?

**Comment by lianup** [comment]
> 

Thanks. I decided to put the configuration file in `gradle.properties` and not use dependabot for now.

**Comment by binkley** [comment]
@lianup  Cool. You'll find that good team practice should include running `./gradlew dependencyUpdates` locally on a schedule (weekly, daily, whatever makes sense) to pick up **security** fixes in dependencies & plugins.
