### ISSUE TITLE
"Intelligent laziness is a virtue." link tries to sell me bathsalts?

### ISSUE THREAD

**Issue by bradtaniguchi** [binkley/modern-java-practices#252]
Hello, I was skimming over the README, and realized there's a dead/incorrect link. 

The following link: `[Intelligent laziness is a virtue](http://threevirtues.com/).` redirects me to a place that sells bath salts?

Link is here in the code (couldn't get the permalink atm):
https://github.com/binkley/modern-java-practices/blame/master/README.md#L299

**Comment by boxleytw** [comment]
README fixed in commit dfe569c685afea723004198e204f2111677afb20
Credit to @bradtaniguchi
