### ISSUE TITLE
Upgrade to Gradle 8

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#358]
Note that "test-sets" plugin used for integration tests relies on removed features available in Gradle 7 and prior:

https://github.com/unbroken-dome/gradle-testsets-plugin/issues/131#issuecomment-1449769358

Part of this issue is to switch to the "jvm-test-suite" plugin:
https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html
It's not as elegant as "test-sets", so research if there is a 3rd-party plugin that wraps up the work for the new API.

**Comment by binkley** [comment]
This is now working with Gradle 8.7 and PMD 6.x, and I have a working local build for PMD 7.x with JDK 21.

**Comment by binkley** [comment]
@sgammon ☝️

**Comment by sgammon** [comment]
@binkley sounds good! 😁
