### ISSUE TITLE
Update to JDK 21

### ISSUE THREAD

**Issue by krzyk** [binkley/modern-java-practices#430]
It's been 4 months since JDK 21 release, it would be good to update project (and README) to use it.

Also I'm not sure that the wordings in README:

1.
> Java 17 is the most current LTS ("long-term support") version

Should be more like:
> Java 21 is the most current version that has LTS builds available

Because Java per se doesn't have LTS, only the distribuitions/builds of Java have LTS.

2.

> In this project, you'll see the choice of Java 17 as this is the version to recommend in production.

Why is 18 or 19 a bad choice? There is nothing inherently bad in those versions, they are not less tested or "beta". The only difference is that none of the vendors publishes security patches to them after the new version is released -> forcing to do the upgrades every 6 months, which is a good practice.

I would drop the "recommend in production" unless a good explanation is given.

**Comment by binkley** [comment]
@krzyk @sgammon
I think I've brought the repo up-to-date for JDK 21.
Krzysztof, I'm reviewing your comments, and want to update the writing to align. You have a lot of good points.

**Comment by binkley** [comment]
@krzyk @sgammon @sl4mmy 
Do either of you (Krzysztof, Sam) have interest in being contributors on the repo (change of GitHub permissions)?
My goal to to eventually produce an open-license book from these materials.

I'm looking for coauthors especially in areas that I less knowledgeable.

**Comment by sgammon** [comment]
@binkley Sure! I would be happy to help. If you want me to take on some aspect of the codebase, just let me know, or I can be available on-demand for reviews and other stuff like that.

**Comment by binkley** [comment]
@sgammon 
The latest code uses JDK 21.
I checked `pom.xml`, `gradle*`, and `.java-version`.

**Comment by binkley** [comment]
@sgammon 
I'm experimenting with a Kanban card wall for the project.
https://github.com/users/binkley/projects/1/views/1

In a team setting this makes sense; with a small project like this, and individual contributors, perhaps not so much. I want to explore how "Projects" work in GitHub, and see if they are sensible to use for larger projects, or for other teams.

**Comment by sgammon** [comment]
@binkley I love the projects feature! Let me know if you'd like me to participate.

**Comment by binkley** [comment]
@sgammon You should be able to freely use the card wall &mdash; I hope I have permissions right!
Before moving items into the Backlog, let have a discussion on the GitHub issue in comments.
I made a first pass at prioritizing (in Agile terms, I'm the "product owner").
