### ISSUE TITLE
Fix links for performance profiles

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#453]
~~Show internal HTML links for performance profiles as rendered (not to be confused with dynamic) HTML not as raw HTML.~~

- Show all command options available
- Provide of examples of HTML, JSON, CONSOLE
- Mention that HTML won't render correctly in the wiki

Look at the file [Monitor and reporting your build page](https://github.com/binkley/modern-java-practices/wiki/Monitoring-and-reporting-your-build).  Note the [SARIF](https://sarifweb.azurewebsites.net/) [examples](https://github.com/binkley/modern-java-practices/wiki/Monitoring-and-reporting-your-build#sarif-examples). For these examples we just want to see the contents of the file.

[how to run perf profiles and also the page to update the links on](https://github.com/binkley/modern-java-practices/wiki/Performance-problems)

**Comment by jwlibby** [comment]
Github wiki pages support some html tags but not all.  There is an open issue for them to provide better support for html pages but no response from the github folks.  So we may have to consider a different approach.  A few possible solutions: 

- github pages (a cdn solution basically, not affilitated with github.  More info on github.io)
- there are some utilities out there to convert html to md.  As far as I can tell these are either available as command line tools or an api that you can use in a project to write some java to do it yourself.  
- maven profiler reporter has output formats (in addition to the default of html) for json and console.  It might be possible to convert from these formats but I think the html format is probably the closest to markdown

**Comment by binkley** [comment]
@jwlibby How did you translate to Markdown for the examples? Looks great!

**Comment by binkley** [comment]
Conversion to Markdown was by hand.

In future, there are some nice tools (pandoc, others).
