### ISSUE TITLE
Readability of function name -- system lambda

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#483]
@jwlibby I moved this card to review. Essentially: review PR https://github.com/binkley/modern-java-practices/pull/601.
If you're OK with the PR, merge and this card is done.
Else, we should move the card back and discuss.

----

https://github.com/binkley/modern-java-practices/blob/master/src/integrationTest/java/demo/ApplicationTest.java

Alternatives for Stephan Birkner's system lambda library -- method names are obscure.

## Refs
- https://openwritings.net/pg/java/how-capture-and-store-console-output-systemoutprintln -- roll our own implementation
- https://github.com/binkley/modern-java-practices/blob/replace-system-lambda/src/test/java/demo/TerminalContext.java - example code of rolling our own capture of stdout/stderr for tests

**Comment by binkley** [comment]
@jwlibby What do you think of rolling our own replacement functions for "system-lambda"? We don't need the full feature set.
I do like mentioning the library in the page on integration testing, however: it is hard to find online docs for testing console output.

**Comment by jwlibby** [comment]
looked at this again, I'm fine w it
