### ISSUE TITLE
Try out Qulice

### ISSUE THREAD

**Issue by jwlibby** [binkley/modern-java-practices#490]
Try out Qulice and see what you think. When evaluating refer to the questions in https://github.com/binkley/modern-java-practices/issues/462 and upon completion add your pros and cons for this plugin as a comment to the aforementioned story. Plugin link: [Qulice](https://github.com/yegor256/qulice)

Note: Name is short for "quality police".

### Book

Do mention and link to Qualice but mention drawbacks. And do not provide in the Gradle or Maven builds.

### QA

As expected from previous experience, Qulice is _very strict_, and may not fit team agreements. Qulice is worth mentioning but with caution that teams adopt the strict standards. (An example: test methods should be marked `final`; this is true, but many teams may not want failures from this.)

See the "Use static analysis" page for writing update.

**Comment by binkley** [comment]
Out of the box, it changes PMD settings (correctly if very strictly), and complains about plain JUnit assert usage.
These cause multiple failures when the code base isn't following Qualice preferences.
