### ISSUE TITLE
Move wiki images into an image folder

### ISSUE THREAD

**Issue by jwlibby** [binkley/modern-java-practices#495]
I created a folder at the root of the wiki repo called `/img`.  Move all existing images of the wiki into this folder and update any references to said images to include the `/img` folder in its path.

**Comment by binkley** [comment]
This is a nice solution!
What I like best is that it keeps images in the same repo as the markdown, so if we want to move from GH wiki to another hosting solution, or if a publisher wants everything in one ZIP file, we have everything in one place.

**Comment by binkley** [comment]
Looks great!
```bash
for x in img/* ; do grep ${x#img/} *.md ; done | grep -v '\./img/'
```
produces no results -- that is, every place referring to one of the image files always does so using the `./img/` path prefix.

**Comment by binkley** [comment]
I moved the SVG files.
