### ISSUE TITLE
Using Batect on GitHub Actions

### ISSUE THREAD

**Issue by charleskorn** [binkley/modern-java-practices#5]
Thanks for pulling this together @binkley, it's a great resource.

I'm interested in understanding more about this comment in the readme:

> Do not run Batect in your CI pipeline directly: use GitHub Actions (or GitLab equivalent). Batect is for your local build. (This is the classic "Docker in Docker" issue, and there are ways address this , if it is important for your team.)

I haven't seen any issues with running Batect inside GitHub Actions - have you encountered any issues? From what I understand, GitHub Actions spins up an ephemeral virtual machine, not a container, so there shouldn't be any issues with Docker in Docker.

I strongly encourage teams to use Batect both locally and on CI - this ensures that the environment remains consistent in both places, making it easier to reproduce issues (or catch problems before they even become issues).

**Comment by binkley** [comment]
Oh, hey, thank you!  I have not tried it because my past history with DnD (docker-in-docker) was so poor, and at least as of a few years back, most key Docker advice recommended against it.

I need to update my experience and opinion.
