### ISSUE TITLE
Move example files into their own directory

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#515]
Just like with images, put the example output files into their own directory.
Move them to `etc`.

This card cannot be fully completed. GitHub does not support markdown pages in subdirectories.
See: https://github.com/orgs/community/discussions/23914#discussioncomment-5447162

**Comment by jwlibby** [comment]
To be fair, it kind of makes sense that you can't have subfolders on a wiki, in that a wiki is meant to be non-hierarchical.  We are basically using a wiki to make something that is meant to be read linearly and has a hierarchical structure.  Wikis inherently are neither of these.  Marking as complete as we already have other cards to consider moving off of the wiki.
