### ISSUE TITLE
Remove redundant title from files

### ISSUE THREAD

**Issue by jwlibby** [binkley/modern-java-practices#518]
Remove redundant title from files. Fix cycle time page to follow convention

**Comment by jwlibby** [comment]
Redundant title removed from each .MD file and each markdown title leveled up one hashmark.  Note: Cycle-time.md seems to have an inconsistent styling on the number of hashes on titles.  Not sure if this was intentional but we can create another card to fix if need be.  For now I made the changes without discrimination across all the MD files in the wiki

**Comment by binkley** [comment]
I fixed the Cycle Time page.
