### ISSUE TITLE
Reorg sidebar

### ISSUE THREAD

**Issue by jwlibby** [binkley/modern-java-practices#520]
This is an ongoing card we've talked about and worked on. I don't think we'll have a definitive answer in one card, so I'm unsure how to show that.
Perhaps it's an _Epic_?

Maybe a script or easy way to get a "table of contents" from the existing MD files in their proper order?
- See `etc/wiki-outline.py` in the wiki repo

Include a link (full, not relative, so usable outside the wiki repo).

### Out of scope

re #516 we need to move dependency management into pipeline topics, pretty early.  Move setup CI into getting started.  Maybe merge setup ci and keep local consistent with ci. Or its own page

**Comment by binkley** [comment]
QA: The code repo `README.md` is now updated using output from the `wiki-outline.py` script.
