### ISSUE TITLE
Javax annotation dependency @Nonnull should not rely on plugin dependencies

### ISSUE THREAD

**Issue by binkley** [binkley/modern-java-practices#595]
Turning off the Spotbugs plugin in the Maven build breaks the javax annotations (`@Nonnull`).
The code should **not** depend on the plugins to compile.

- [ ] When the Maven build runs, and SpotBugs is disabled, the build should still compile

## Tech analysis
We are missing the javax.annotations dependency, and rely on the spotbugs-annotations dependency to provide them.
Add the dependency, and update the imports, and see if `Nonnull` got renamed (ie, `NonNull`, etc).
Otherwise, this is short work.

## Further
Turn off all plugins, and check the code compiles.

**Comment by jwlibby** [comment]
Nothing to review for this, spotbugs is necessary.  Also this was only done in a test branch so no changes that broke anything were committed to master
